#!/usr/bin/env sh

yabai -m config \
	top_padding 5 \
	bottom_padding 5 \
	left_padding 5 \
	right_padding 5 \
	window_zoom_persist on \
	window_shadow on \
	window_gap 10 \
	window_animation_duration 0.0 \
	window_animation_easing ease_out_circ \
	window_opacity_duration 0.0 \
	window_opacity on \
	active_window_opacity 1.0 \
	normal_window_opacity 0.98 \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# Sketchybar
yabai -m signal --add event=window_created      action="command -v sketchybar &> /dev/null && sketchybar --trigger yabai_window_created"
# yabai -m signal --add event=window_destroyed    action="command -v sketchybar &> /dev/null && sketchybar --trigger yabai_window_destroyed"
yabai -m signal --add event=window_focused      action="command -v sketchybar &> /dev/null && sketchybar --trigger yabai_window_focused"
yabai -m signal --add event=window_resized      action="command -v sketchybar &> /dev/null && sketchybar --trigger yabai_window_resized"
yabai -m signal --add event=window_moved        action="command -v sketchybar &> /dev/null && sketchybar --trigger yabai_window_moved"
yabai -m signal --add event=application_visible action="command -v sketchybar &> /dev/null && sketchybar --trigger yabai_application_visible"
# yabai -m signal --add event=application_hidden  action="command -v sketchybar &> /dev/null && sketchybar --trigger yabai_application_hidden"

yabai -m rule --add app="^(System Preferences|Alacritty|1Password|Messages)$" manage=off

yabai -m rule --apply # https://github.com/koekeishiya/yabai/issues/2178

command -v sketchybar &> /dev/null && sketchybar --trigger yabai_loaded
echo "yabai configuration loaded.."
osascript -e "display notification \"yabai configuration loaded..!\" with title \"yabai\""
