#!/usr/bin/env sh

yabai -m config \
	top_padding 5 \
	bottom_padding 5 \
	left_padding 5 \
	right_padding 5 \
	window_zoom_persist on \
	window_shadow on \
	window_gap 10 \
	window_animation_duration 0.0 \
	window_animation_easing ease_out_circ \
	window_opacity_duration 0.0 \
	window_opacity on \
	active_window_opacity 1.0 \
	normal_window_opacity 0.98 \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

yabai -m rule --add app="^(System Preferences|Alacritty|1Password|Messages)$" manage=off

yabai -m rule --apply # https://github.com/koekeishiya/yabai/issues/2178

echo "yabai configuration loaded.."
osascript -e "display notification \"yabai configuration loaded..!\" with title \"yabai\""
