{
  config,
  pkgs,
  inputs,
  ...
}:

let
  user = config.myOptions.user.username;
in
{
  imports = [
    inputs.stylix.homeModules.stylix
    inputs.nix-flatpak.homeManagerModules.nix-flatpak
    inputs.plasma-manager.homeModules.plasma-manager
    ../../modules/shared/home/dotfiles.nix
    ../../modules/shared/home
  ];

  myOptions = {
    sshSignProgram = "/opt/1Password/op-ssh-sign";
    gitCredentialHelper = "store";
  };

  nixpkgs.config = {
    allowUnfree = true;
  };

  stylix = {
    enable = true;
    base16Scheme = config.lib.myTheme.schemeYaml;
    polarity = config.lib.myTheme.polarity;
    cursor = {
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Classic";
      size = 28;
    };
    targets = {
      starship.enable = true;
      tmux.enable = true;
      fish.enable = true;
      fzf.enable = true;
      bat.enable = true;
      wezterm.enable = true;
      ghostty.enable = true;
      zellij.enable = true;
      kde.enable = true;
      neovim.enable = false;
    };
  };

  home = {
    username = user;
    homeDirectory = "/home/${user}";
    packages = pkgs.callPackage ./packages.nix { } ++ [
      inputs.claude-code-nix.packages.x86_64-linux.default
    ];

    sessionVariables = {
      EDITOR = "nvim";
      VISUAL = "nvim";
      PAGER = "less";
      CLAUDE_CONFIG_DIR = "$HOME/.config/claude";
    };

    sessionPath = [
      "$HOME/go/bin"
    ];

    stateVersion = "24.11";
  };

  programs.plasma = {
    enable = true;
    workspace = {
      # colorScheme + cursor are generated by stylix.targets.kde +
      # stylix.cursor. iconTheme and windowDecorations are not
      # palette-driven, so they stay explicit here.
      iconTheme = "Papirus-Dark";
      theme = "breeze-dark";
      windowDecorations = {
        library = "org.kde.breeze";
        theme = "Breeze";
      };
    };

    configFile = {
      kwinrc.TabBox.HighlightWindows = false;
      breezerc.Windeco.ButtonSize = "ButtonSmall";
    };

    kwin.virtualDesktops = {
      number = 2;
      rows = 1;
      names = [
        "1"
        "2"
      ];
    };

    shortcuts.kwin = {
      "Switch to Desktop 1" = "Alt+1";
      "Switch to Desktop 2" = "Alt+2";
      "Window to Desktop 1" = "Alt+Shift+1";
      "Window to Desktop 2" = "Alt+Shift+2";
    };

    input.keyboard.layouts = [
      { layout = "norwerty"; }
    ];

  };

  qt = {
    enable = true;
    platformTheme.name = "kvantum";
    style.name = "kvantum";
  };

  services.flatpak.enable = true;
  services.flatpak.packages = [
    "io.github.zen_browser.zen"
    "com.discordapp.Discord"
    "com.slack.Slack"
    "com.visualstudio.code"
    "community.pathofbuilding.PathOfBuilding"
    "com.github.iwalton3.jellyfin-media-player"
    "im.riot.Riot" # Element (Matrix client)
  ];

  # Disable AirPlay (RAOP) sound outputs from appearing in PipeWire
  # https://discussion.fedoraproject.org/t/airplay-audio-outputs-discovery-enabled-by-default/166328
  xdg.configFile."pipewire/pipewire.conf.d/90-disable-raop.conf".text = ''
    context.properties = {
        module.raop = false
    }
  '';

  xdg.desktopEntries.awakened-poe-trade = {
    name = "Awakened PoE Trade";
    exec = "env XDG_SESSION_TYPE=x11 ${config.home.homeDirectory}/Applications/Awakened-PoE-Trade.AppImage --sandbox --force-device-scale-factor=1";
    terminal = false;
    type = "Application";
    categories = [
      "Game"
      "Utility"
    ];
  };

  xdg.configFile."autostart/1password.desktop".text = ''
    [Desktop Entry]
    Name=1Password
    Exec=/opt/1Password/1password --silent
    Terminal=false
    Type=Application
    Icon=1password
    StartupWMClass=1Password
    Comment=Password manager and secure wallet
    X-GNOME-Autostart-enabled=true
  '';

  # Norwerty keyboard layout (US QWERTY with Norwegian characters)
  # https://tobiasvl.github.io/norwerty/
  xdg.configFile."xkb/symbols/norwerty".text = ''
    // Norwerty by Tobias V. Langhoff
    // Based on Swerty by Johan E. Gustafsson
    default partial alphanumeric_keys
    xkb_symbols "basic" {

        name[Group1]="Norwegian (Norwerty)";

        key <TLDE>  { [     grave,	asciitilde, section, onehalf ]	};
        key <AE01>	{ [         1,     exclam   	     	     ]  };
        key <AE02>	{ [         2,         at,  quotedbl 	     ]	};
        key <AE03>	{ [         3, numbersign,  sterling 	     ]	};
        key <AE04>	{ [         4,     dollar,  currency 	     ]	};
        key <AE05>	{ [         5,    percent,  EuroSign 	     ]	};
        key <AE06>	{ [         6, asciicircum, dead_circumflex  ]	};
        key <AE07>	{ [         7,  ampersand,  braceleft        ]	};
        key <AE08>	{ [         8,   asterisk,  bracketleft	     ]	};
        key <AE09>	{ [         9,  parenleft,  bracketright     ]	};
        key <AE10>	{ [         0, parenright,  braceright 	     ]	};
        key <AE11>	{ [     minus, underscore,  dead_diaeresis,  dead_circumflex ]  };
        key <AE12>	{ [     equal,       plus,  dead_tilde 	     ]	};

        key <AD01>	{ [         q,          Q   		     ] 	};
        key <AD02>	{ [         w,          W 		     ]	};
        key <AD03>	{ [         e,          E,  EuroSign  	     ]	};
        key <AD04>	{ [         r,          R   		     ]	};
        key <AD05>	{ [         t,          T 		     ]	};
        key <AD06>	{ [         y,          Y 		     ]	};
        key <AD07>	{ [         u,          U 		     ]	};
        key <AD08>	{ [         i,          I 		     ]	};
        key <AD09>	{ [         o,          O,  braceleft	     ]	};
        key <AD10>	{ [         p,          P,  braceright 	     ]	};
        key <AD11>	{ [	    aring,  Aring,  bracketleft,  braceleft ]  };
        key <AD12>	{ [dead_acute, dead_grave,  bracketright,  braceright ]  };
        key <AC01>	{ [         a,          A   		     ]	};
        key <AC02>	{ [         s,          S 		     ]	};
        key <AC03>	{ [         d,          D 		     ]	};
        key <AC04>	{ [         f,          F 		     ]	};
        key <AC05>	{ [         g,          G 		     ]	};
        key <AC06>	{ [         h,          H 		     ]	};
        key <AC07>	{ [         j,          J 		     ]	};
        key <AC08>	{ [         k,          K 		     ]	};
        key <AC09>	{ [         l,          L 		     ]	};
        key <AC10>	{ [    oslash,   Ooblique,     semicolon,  colon ]  };
        key <AC11>	{ [        ae,         AE,    apostrophe,  quotedbl ]  };

        key <BKSL>	{ [ backslash,        bar		     ]	};
        key <AB01>	{ [         z,          Z 		     ]	};
        key <AB02>	{ [         x,          X 		     ]	};
        key <AB03>	{ [         c,          C 		     ]	};
        key <AB04>	{ [         v,          V 		     ]	};
        key <AB05>	{ [         b,          B 		     ] 	};
        key <AB06>	{ [         n,          N 		     ]	};
        key <AB07>	{ [         m,          M,  mu		     ]	};
        key <AB08>	{ [     comma,       less  		     ]	};
        key <AB09>	{ [    period,    greater,  colon	     ]	};
        key <AB10>	{ [     slash,   question 		     ] 	};

        include "level3(ralt_switch)"
    };
  '';

  xdg.configFile."xkb/rules/evdev.xml".text = ''
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">
    <xkbConfigRegistry version="1.1">
      <layoutList>
        <layout>
          <configItem>
            <name>norwerty</name>
            <shortDescription>no</shortDescription>
            <description>Norwegian (Norwerty)</description>
            <languageList>
              <iso639Id>nor</iso639Id>
            </languageList>
          </configItem>
        </layout>
      </layoutList>
    </xkbConfigRegistry>
  '';

}
