return {}
-- return {
--   "nvim-telescope/telescope.nvim",
--   opts = {
--     defaults = {
--       mappings = {
--         i = {
--           ["<esc>"] = require("telescope.actions").close,
--           ["<c-e>"] = { "<esc>", type = "command" },
--         },
--       },
--     },
--   },
-- }
