# Agent git identity: HTTPS with a per-owner token, instead of the operator's
# SSH key.
#
# The interactive gitconfig rewrites https://github.com/ to ssh://, so every git
# operation authenticates with an unscoped user SSH key and a scoped token has
# no effect on what an agent can push. Agents therefore get their own
# GIT_CONFIG_GLOBAL pointing at the file rendered here — HTTPS only, credentials
# from a per-owner token file, no fallback.
#
# Two mechanisms are load-bearing:
#   - GIT_CONFIG_SYSTEM must also be neutralised. It is a separate scope that
#     GIT_CONFIG_GLOBAL does not override, and git's own etc/gitconfig sets a
#     platform credential helper (osxkeychain) that satisfies pushes from cache
#     on its own, masking a bad token.
#   - `gh auth git-credential` is NOT usable as the helper: with an invalid
#     token in the environment it falls back to the keyring account and hands
#     git the operator's broad token, so scope would never bind.
#
# An owner absent from ownerTokens gets no credential through the managed
# defaults. Repository access is still bounded by the PAT's own owner,
# repository, and permission scopes: routing prevents accidental credential
# crossover and operator fallback, but is not an independent security boundary.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.myOptions.agentGit;
  gitAuthor = config.myOptions.gitAuthors.agent;

  enabled = cfg.ownerTokens != { };

  agentGithubRouter =
    if cfg.package != null then
      cfg.package
    else
      pkgs.callPackage ../../../../packages/agent-github-router { };

  ownerEntries = lib.mapAttrsToList (owner: tokenFile: {
    owner = lib.toLower owner;
    credential = "owner:${lib.toLower owner}";
    inherit tokenFile;
  }) cfg.ownerTokens;

  normalizedOwners = map (entry: entry.owner) ownerEntries;

  ownerCredentials = builtins.listToAttrs (
    map (entry: lib.nameValuePair entry.credential { inherit (entry) tokenFile; }) ownerEntries
  );

  ownerRoutes = builtins.listToAttrs (
    map (entry: lib.nameValuePair entry.owner entry.credential) ownerEntries
  );

  credentials =
    ownerCredentials
    // lib.optionalAttrs (cfg.projectsToken != "") {
      projects.tokenFile = cfg.projectsToken;
    };

  agentAliases = pkgs.writeText "agent-git-aliases" (
    builtins.readFile ../../../../dotfiles/git-extra/aliases.gitconfig
  );

  agentGhConfig = pkgs.writeTextDir "config.yml" ''
    version: 1
  '';

  routerConfig = {
    version = 1;
    executables = {
      gh = lib.getExe pkgs.gh;
      git = lib.getExe pkgs.git;
    };
    ghConfigDir = agentGhConfig;
    inherit credentials ownerRoutes;
    projectsCredential = if cfg.projectsToken != "" then "projects" else null;
  };

  # This config must stay independent of agentGitconfig: agentGitconfig embeds
  # its path in the Git credential helper command.
  credentialRouterConfig = pkgs.writeText "agent-github-credential-router.json" (
    builtins.toJSON (routerConfig // { allowedGitConfigs = [ ]; })
  );

  ghRouterConfig = pkgs.writeText "agent-github-gh-router.json" (
    builtins.toJSON (routerConfig // { allowedGitConfigs = [ agentGitconfig ]; })
  );

  agentGhWrapper = pkgs.writeShellApplication {
    name = "gh";
    text = ''
      case "''${GIT_CONFIG_GLOBAL:-}" in
        "") exec ${lib.getExe pkgs.gh} "$@" ;;
        *) exec ${lib.getExe agentGithubRouter} --config ${ghRouterConfig} gh -- "$@" ;;
      esac
    '';
  };

  agentGh = pkgs.symlinkJoin {
    name = "gh-agent-aware-${pkgs.gh.version}";
    paths = [ pkgs.gh ];
    inherit (pkgs.gh) meta;
    postBuild = ''
      rm "$out/bin/gh"
      ln -s ${lib.getExe agentGhWrapper} "$out/bin/gh"
    '';
  };

  # insteadOf only rewrites literal prefixes, while Git accepts other SSH URL
  # spellings from remotes and submodules. Fail closed before an ambient SSH
  # agent can satisfy any form the ergonomic rewrites miss.
  sshTransportDisabled = pkgs.writeShellApplication {
    name = "agent-git-ssh-disabled";
    text = ''
      printf '%s\n' 'agent-git: ssh transport disabled; use https' >&2
      exit 1
    '';
  };

  # Hand-written INI rather than generators.toGitINI: the credential subsection
  # and the repeated insteadOf keys are easier to keep exact this way, and this
  # file is a security control worth reading literally.
  agentGitconfig = pkgs.writeText "agent-gitconfig" ''
    # Generated by agent-git.nix. Lives in the store, so it is read-only —
    # `git config --global` fails for agents by design, which stops a session
    # from re-adding the ssh rewrite this file exists to remove. Not a boundary
    # (`git -c` and GIT_CONFIG_GLOBAL are still the agent's to set), just the
    # right default.
    [user]
      name = ${gitAuthor.name}
      email = ${gitAuthor.email}
    ${lib.optionalString (cfg.signingKeyFile != "") ''
      signingkey = ${cfg.signingKeyFile}
    ''}
    [credential]
      useHttpPath = true
    [credential "https://github.com"]
      helper = !${lib.getExe agentGithubRouter} --config ${credentialRouterConfig} credential
    [url "https://github.com/"]
      insteadOf = ssh://git@github.com/
      insteadOf = git@github.com:
    ${lib.optionalString (cfg.signingKeyFile != "") ''
      [gpg]
        format = ssh
      [gpg "ssh"]
        program = ssh-keygen
      ${lib.optionalString (cfg.allowedSignersFile != "") ''
        allowedSignersFile = ${cfg.allowedSignersFile}
      ''}
      [commit]
        gpgsign = true
      [tag]
        gpgsign = true
    ''}
    [init]
      defaultBranch = main
    [pull]
      rebase = true
      default = current
    [push]
      default = current
    [rerere]
      enabled = true
    [core]
      editor = nvim
      sshCommand = ${lib.getExe sshTransportDisabled}
    # Ensure port-qualified URLs invoke the blocker instead of Git rejecting
    # the custom command as an argument-less "simple" SSH variant first.
    [ssh]
      variant = ssh
    [filter "lfs"]
      clean = git-lfs clean -- %f
      process = git-lfs filter-process
      required = true
      smudge = git-lfs smudge -- %f
    [delta]
      hyperlinks = true
      keep-plus-minus-markers = true
      line-numbers = true
      navigate = true
      pager = less
      side-by-side = false
    [interactive]
      diffFilter = ${lib.getExe pkgs.delta} --color-only
    [pager]
      blame = ${lib.getExe pkgs.delta}
      diff = ${lib.getExe pkgs.delta}
      log = ${lib.getExe pkgs.delta}
      show = ${lib.getExe pkgs.delta}
    [include]
      path = ${agentAliases}
  '';
in
lib.mkIf enabled {
  assertions = [
    {
      assertion = lib.length normalizedOwners == lib.length (lib.unique normalizedOwners);
      message = "myOptions.agentGit.ownerTokens contains owner names that differ only by case";
    }
  ];

  # Options live in shared/options.nix — the myOptions tree is forwarded into
  # home-manager, so a system-only declaration breaks HM's copy.
  myOptions.agentGit = {
    ghPackage = agentGh;
    gitconfigPath = "${agentGitconfig}";
  };
}
