version = 5

[[hotkeys]]
binding = "Option+H"
id = "focus.left"

[[hotkeys]]
binding = "Option+J"
id = "focus.down"

[[hotkeys]]
binding = "Option+K"
id = "focus.up"

[[hotkeys]]
binding = "Option+L"
id = "focus.right"

[[hotkeys]]
binding = "Option+Shift+H"
id = "move.left"

[[hotkeys]]
binding = "Option+Shift+J"
id = "move.down"

[[hotkeys]]
binding = "Option+Shift+K"
id = "move.up"

[[hotkeys]]
binding = "Option+Shift+L"
id = "move.right"

[[hotkeys]]
binding = "Control+Option+Shift+K"
id = "moveWindowToWorkspaceUp"

[[hotkeys]]
binding = "Control+Option+Shift+J"
id = "moveWindowToWorkspaceDown"

[[hotkeys]]
binding = "Control+Option+Shift+H"
id = "moveColumn.left"

[[hotkeys]]
binding = "Control+Option+Shift+L"
id = "moveColumn.right"

[[hotkeys]]
binding = "Option+Shift+T"
id = "toggleWorkspaceLayout"
