{
  config,
  lib,
  pkgs,
  ...
}:

let
  configPath = config.myOptions.dotfiles.repoRoot;
  inherit (config.myOptions.dotfiles) wmBackend;
  mutable = config.myOptions.mutableDotfiles;

  # Names to skip at every level of a recursive dotfile traversal.
  # These are repo-housekeeping files that currently leak into
  # ~/.config/<app>/ as a side effect of whole-dir symlinks; filter them
  # out now that we enumerate per-file.
  defaultSkip = [
    "LICENSE"
    "README.md"
    ".git"
    ".gitignore"
    ".gitattributes"
    ".DS_Store"
    "stylua.toml"
    "selene.toml"
    "lua.yml"
    ".luarc.json"
  ];

  # Recurse a source dir, returning a list of file paths relative to the
  # source dir root. Filters out skip names at every level.
  listFilesRec =
    skip: srcPath:
    let
      entries = builtins.readDir srcPath;
      visit =
        name: type:
        if builtins.elem name skip then
          [ ]
        else if type == "directory" then
          map (sub: "${name}/${sub}") (listFilesRec skip "${srcPath}/${name}")
        else if type == "regular" || type == "symlink" then
          [ name ]
        else
          [ ];
    in
    lib.concatLists (lib.mapAttrsToList visit entries);

  # Build xdg.configFile entries for every file under a dotfile source dir.
  #   srcRel       — path relative to public/dotfiles/ (e.g. "nvim", "git-extra")
  #   xdgRel       — path relative to ~/.config/    (e.g. "nvim", "git/extra")
  #   skip         — basenames to skip at any depth (default: defaultSkip)
  #   extraExclude — source-relative paths to skip entirely (e.g.
  #                  [ "colors.sh" ] for sketchybar — Nix-generated)
  mkPerFileDots =
    {
      srcRel,
      xdgRel,
      skip ? defaultSkip,
      extraExclude ? [ ],
    }:
    let
      absSrc = ../../../dotfiles + "/${srcRel}";
      files = builtins.filter (f: !(builtins.elem f extraExclude)) (listFilesRec skip absSrc);
      entry = file: {
        name = "${xdgRel}/${file}";
        value = {
          source =
            if mutable then
              config.lib.file.mkOutOfStoreSymlink "${configPath}/dotfiles/${srcRel}/${file}"
            else
              ../../../dotfiles + "/${srcRel}/${file}";
        };
      };
    in
    builtins.listToAttrs (map entry files);

  # Single-file dotfile entries (xdg-relative key, dotfile-relative value).
  # For literal file-to-file mappings where the source isn't a directory.
  baseSingleDots = {
    "lazygit/config.yml" = "lazygit.yml";
  };

  yabaiSingleDots = { };

  skhdSingleDots =
    lib.optionalAttrs (wmBackend != "none") {
      "skhd/common.skhd" = "skhd/common.skhd";
      "skhd/builtin-keyboard.skhd" = "skhd/builtin-keyboard.skhd";
    }
    // lib.optionalAttrs (wmBackend == "yabai") {
      "skhd/yabai.skhd" = "skhd/yabai.skhd";
    }
    // lib.optionalAttrs (wmBackend == "omniwm") {
      "skhd/omniwm.skhd" = "skhd/omniwm.skhd";
    };

  skhdEntryPoint = lib.optionalAttrs (wmBackend != "none") {
    "skhd/skhdrc" = {
      text =
        lib.concatStringsSep "\n" (
          [
            ''.load "builtin-keyboard.skhd"''
            ''.load "common.skhd"''
          ]
          ++ lib.optional (wmBackend == "yabai") ''.load "yabai.skhd"''
          ++ lib.optional (wmBackend == "omniwm") ''.load "omniwm.skhd"''
        )
        + "\n";
    };
  };

  # Per-app per-file dotfile blocks. Each maps a whole source dir into
  # individual xdg.configFile entries.
  baseFileDots =
    mkPerFileDots {
      srcRel = "nvim";
      xdgRel = "nvim";
    }
    // mkPerFileDots {
      srcRel = "ghostty";
      xdgRel = "ghostty";
    }
    // mkPerFileDots {
      srcRel = "zellij";
      xdgRel = "zellij";
      # layouts/zjstatus.kdl is Nix-generated by terminal-themes.nix
      # (palette-driven). Excluding here avoids the symlink-vs-generated
      # collision.
      extraExclude = [ "layouts/zjstatus.kdl" ];
    }
    // mkPerFileDots {
      srcRel = "sketchybar";
      xdgRel = "sketchybar";
      # colors.sh becomes Nix-generated in Phase 2.2 of the global-theme
      # work — exclude here so the symlink doesn't collide with the
      # generated file.
      extraExclude = [ "colors.sh" ];
    }
    // mkPerFileDots {
      srcRel = "wezterm/extra";
      xdgRel = "wezterm/extra";
    }
    // mkPerFileDots {
      srcRel = "git-extra";
      xdgRel = "git/extra";
    };

  yabaiFileDots = mkPerFileDots {
    srcRel = "yabai";
    xdgRel = "yabai";
  };

  aerospaceFileDots = mkPerFileDots {
    srcRel = "aerospace";
    xdgRel = "aerospace";
  };

  # OmniWM settings are GUI-managed only: the app writes settings.toml via
  # atomic rename(2), which replaces symlinks with real files. No upstream
  # support for symlinks, separate hotkey config, or IPC hotkey toggle yet.
  # Hotkeys we control live in skhd (omniwm.skhd); OmniWM's native hotkeys
  # are configured through its GUI.
  omniwmFileDots = { };

  singleSymlink = _key: value: {
    source =
      if mutable then
        config.lib.file.mkOutOfStoreSymlink "${configPath}/dotfiles/${value}"
      else
        ../../../dotfiles + "/${value}";
  };

  singleDots =
    baseSingleDots // skhdSingleDots // (if wmBackend == "yabai" then yabaiSingleDots else { });

  fileDots =
    baseFileDots
    // (if wmBackend == "yabai" then yabaiFileDots else { })
    // (if wmBackend == "aerospace" then aerospaceFileDots else { })
    // (if wmBackend == "omniwm" then omniwmFileDots else { });
in
{
  imports = [
    ./ai/opencode.nix
    ./ai/oh-my-opencode-slim.nix
    ./ai/claude-powerline.nix
  ];

  # wmBackend is darwin-only — the enum values (yabai/aerospace/omniwm) are
  # macOS WMs. Bridged in from system-scope by `public/modules/darwin/default.nix`
  # (which mirrors `myOptions.windowManager.backend`). On Linux it stays at
  # "none" and the per-WM dotfile bundles below are simply skipped.
  options.myOptions.dotfiles = {
    wmBackend = lib.mkOption {
      type = lib.types.enum [
        "yabai"
        "aerospace"
        "omniwm"
        "none"
      ];
      default = "none";
      description = ''
        Darwin-only: selects which WM dotfile bundle (yabai/aerospace/omniwm)
        gets symlinked. Set automatically on darwin from
        `myOptions.windowManager.backend`. Must remain "none" on Linux.
      '';
    };
  };

  config = {
    assertions = [
      {
        assertion = wmBackend == "none" || pkgs.stdenv.isDarwin;
        message = ''
          myOptions.dotfiles.wmBackend = "${wmBackend}" is darwin-only.
          yabai/aerospace/omniwm are macOS window managers; setting this on
          Linux would symlink their configs into ~/.config/ with nothing to
          read them.
        '';
      }
    ];
    xdg.configFile = (lib.mapAttrs singleSymlink singleDots) // fileDots // skhdEntryPoint;
  };
}
