# Nvim theme bridge — Nix generates `~/.config/nvim/lua/theme.lua` from
# `myOptions.theme.*` and Stylix's base16 palette. Consumers in the
# dotfile-side colorscheme.lua and theme_reactive.lua require this file
# to get the active scheme name and the palette as `#RRGGBB` strings.
#
# Why not just enable Stylix's neovim target? It rewrites the whole nvim
# config, which conflicts with our live-edit dotfile pattern. The
# theme.lua bridge keeps nvim driven by the same `myOptions.theme.scheme`
# knob without giving up live-editing the rest of the nvim config.
{ config, lib, ... }:

let
  myTheme = config.lib.myTheme;
  c = config.lib.stylix.colors.withHashtag;

  # Map our `myOptions.theme.scheme` enum to the colorscheme name each
  # candidate plugin registers. `:colorscheme <name>` uses this string.
  pluginColorscheme = {
    "rose-pine" = "rose-pine";
    "rose-pine-moon" = "rose-pine-moon";
    "rose-pine-dawn" = "rose-pine-dawn";
    "tokyo-night-dark" = "tokyonight-night";
    "tokyo-night-storm" = "tokyonight-storm";
    "tokyo-night-moon" = "tokyonight-moon";
    "tokyo-night-light" = "tokyonight-day";
    "kanagawa" = "kanagawa-wave";
    "kanagawa-dragon" = "kanagawa-dragon";
    "catppuccin-macchiato" = "catppuccin-macchiato";
    "catppuccin-mocha" = "catppuccin-mocha";
    "catppuccin-frappe" = "catppuccin-frappe";
    "catppuccin-latte" = "catppuccin-latte";
  };

  # All 16 base16 slots, ordered.
  base16Slots = [
    "base00"
    "base01"
    "base02"
    "base03"
    "base04"
    "base05"
    "base06"
    "base07"
    "base08"
    "base09"
    "base0A"
    "base0B"
    "base0C"
    "base0D"
    "base0E"
    "base0F"
  ];

  colorsLua = lib.concatMapStringsSep "\n  " (slot: ''${slot} = "${c.${slot}}",'') base16Slots;
in
{
  config.xdg.configFile."nvim/lua/theme.lua".text = ''
    -- Generated by Nix from myOptions.theme + stylix base16 palette.
    -- Do not edit by hand; change `myOptions.theme.scheme` and rebuild.
    local M = {}

    M.scheme = "${myTheme.scheme}"
    M.polarity = "${myTheme.polarity}"
    M.colorscheme = "${pluginColorscheme.${myTheme.scheme}}"

    M.colors = {
      ${colorsLua}
    }

    return M
  '';
}
