# showy-quota — AI plan quota strip in the status bar, themed from Stylix.
#
# Data path: a supervised `codexbar serve` agent caches provider usage in
# memory, and `showy-quota-fetch` copies it into the shared on-disk renderer
# cache. The CLI remains the fallback when the loopback service is unavailable.
# Serve exists to keep codexbar's ~17.5s Claude collection off the render path.
#
# Exposure: no dashboard token, so `/dashboard/v1/snapshot` fails closed. On a
# loopback bind `/usage` and `/cost` are unauthenticated by design, and they
# return account email, organization and login method alongside the quota
# numbers — all readable by any local process, sandboxed apps included. A token
# would not change that; it gates those routes only on a non-loopback bind. No
# credential is held here; codexbar reads the sessions already on this machine.
#
# Theming: upstream themes are plain `.env` files of `: "${VAR:=hex}"`
# assignments, and the user config dir is searched before the package's own
# share/themes, so a Nix-generated palette drops in as just another theme.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  # Bare hex, no leading '#': the shell palette interpolates these into
  # SketchyBar `0xAARRGGBB` literals and ANSI escapes itself.
  c = config.lib.stylix.colors;
  servePort = 8766;
  serveRequestTimeout = 45;
  # Polling faster than showy-quota's own renderer cache floor buys nothing: the
  # floor still gates how often the tile can change.
  refreshInterval = 120;
in
# SketchyBar is the only surface wired here, so this is macOS-only.
lib.mkIf pkgs.stdenv.hostPlatform.isDarwin {
  home.packages = [
    pkgs.codexbar-cli
    pkgs.showy-quota
  ];

  # showy-quota clamps its own /usage timeout at 60s, so past this the client
  # would stop outwaiting the agent and abandon requests it would have answered.
  assertions = [
    {
      assertion = serveRequestTimeout <= 55;
      message = "showy-quota clamps SHOWY_QUOTA_CODEXBAR_SERVE_USAGE_TIMEOUT_SECONDS at 60; serveRequestTimeout must stay <= 55.";
    }
  ];

  launchd.agents.codexbar-serve = {
    enable = true;
    config = {
      ProgramArguments = [
        (lib.getExe pkgs.codexbar-cli)
        "serve"
        "--host"
        "127.0.0.1"
        "--port"
        (toString servePort)
        "--refresh-interval"
        (toString refreshInterval)
        "--request-timeout"
        (toString serveRequestTimeout)
      ];
      # The Claude probe needs CLAUDE_CONFIG_DIR, and an agent captures its
      # environment once at load. Session-wide `launchctl setenv` is gone after
      # a reboot, so carry the path in the plist rather than inheriting it.
      EnvironmentVariables.CLAUDE_CONFIG_DIR = "${config.xdg.configHome}/claude";
      RunAtLoad = true;
      KeepAlive = true;
      StandardOutPath = "${config.home.homeDirectory}/Library/Logs/codexbar-serve.out.log";
      StandardErrorPath = "${config.home.homeDirectory}/Library/Logs/codexbar-serve.err.log";
    };
  };

  xdg.configFile = {
    # Sourced as shell, not parsed — assignments and comments only.
    #
    # showy-quota refuses to source a config or theme file owned by another uid
    # or writable by group/other. These are store symlinks, and the store is
    # root-owned — but the check stats the *link* (neither BSD nor GNU stat
    # dereferences without -L), which is user-owned and mode 755, so it passes.
    # If upstream ever adds -L it fails soft: a "refusing to source" line on
    # stderr and the stock palette. The fix then is real files, not symlinks.
    "showy-quota/config.env".text = ''
      # Generated by Nix — see modules/shared/home/showy-quota.nix.
      SHOWY_QUOTA_THEME=stylix
      SHOWY_QUOTA_CODEXBAR_BIN=${lib.getExe pkgs.codexbar-cli}

      SHOWY_QUOTA_CODEXBAR_SERVE_URL=http://127.0.0.1:${toString servePort}

      # Upstream's default spawns serve from the bar plugin as a side effect of
      # drawing, unsupervised; launchd owns the lifecycle here instead.
      SHOWY_QUOTA_MANAGE_SERVE=0

      # The client must outwait the agent's own --request-timeout, or it
      # abandons a request the server would still have answered.
      SHOWY_QUOTA_CODEXBAR_SERVE_USAGE_TIMEOUT_SECONDS=${toString (serveRequestTimeout + 5)}

      # Applied per provider while the shared fetch lock is held, so the whole
      # fallback sweep has to stay under the refresh cadence above. codexbar's
      # Claude probe measures ~17.5s — the cost is codexbar's, not the CLI's it
      # wraps (`claude -p /usage` alone returns in ~1.6s), and upstream #2117
      # closed without isolating it — so this leaves headroom over that without
      # letting a stuck sweep outlive the interval.
      SHOWY_QUOTA_CODEXBAR_CLI_TIMEOUT_SECONDS=30

      # A wedged serve (process alive, /usage blocking) is the one failure
      # launchd's KeepAlive cannot see, and MANAGE_SERVE=0 bars showy-quota from
      # recycling it. The shipped default spends 10s per refresh discovering
      # that; this reaches the CLI fallback sooner.
      SHOWY_QUOTA_CODEXBAR_SERVE_TIMEOUT_SECONDS=2
    '';

    # Mirrors the variable set upstream's own themes define. `:=` throughout,
    # so an explicit environment override still wins over the palette.
    "showy-quota/themes/stylix.env".text = ''
      # Generated by Nix from myOptions.theme + the stylix base16 palette.
      # Do not edit by hand; change `myOptions.theme.scheme` and rebuild.
      #
      # Var → base16 slot:
      #   PRIMARY_GOOD base0B   PRIMARY_WARN   base0A   PRIMARY_BAD  base08
      #   PRIMARY_UNKNOWN base03  BG           base00   SURFACE      base01
      #   TRACK        base02   ICON_TEXT      base05   COUNTDOWN    base04
      #   COUNTDOWN_WARN base08  ELAPSED       base0E
      : "''${SHOWY_QUOTA_PALETTE_PRIMARY_GOOD:=${c.base0B}}"
      : "''${SHOWY_QUOTA_PALETTE_PRIMARY_WARN:=${c.base0A}}"
      : "''${SHOWY_QUOTA_PALETTE_PRIMARY_BAD:=${c.base08}}"
      : "''${SHOWY_QUOTA_PALETTE_PRIMARY_UNKNOWN:=${c.base03}}"
      : "''${SHOWY_QUOTA_PALETTE_BG:=${c.base00}}"
      : "''${SHOWY_QUOTA_PALETTE_SURFACE:=${c.base01}}"
      : "''${SHOWY_QUOTA_PALETTE_TRACK:=${c.base02}}"
      : "''${SHOWY_QUOTA_PALETTE_ICON_TEXT:=${c.base05}}"
      : "''${SHOWY_QUOTA_PALETTE_COUNTDOWN:=${c.base04}}"
      : "''${SHOWY_QUOTA_PALETTE_COUNTDOWN_WARN:=${c.base08}}"
      : "''${SHOWY_QUOTA_PALETTE_ELAPSED:=${c.base0E}}"
    '';

    # Upstream's own bootstrap, linked rather than reimplemented: it declares
    # the trigger item and points SketchyBar's `script=` at the plugin beside
    # it in the store. Both ends walk their symlink chain back to the real file
    # before resolving siblings, so linking here still lands in the package
    # root.
    "sketchybar/items/showy_quota.sh".source =
      "${pkgs.showy-quota}/adapters/sketchybar/items/showy_quota.sh";
  };
}
