# Sketchybar palette bridge — Nix generates ~/.config/sketchybar/colors.sh
# from `config.lib.stylix.colors`. Sketchybar plugins and items source
# this file via env.sh; the names and shape (bare assignments, no
# `export`) match what the existing plugin shell scripts expect.
#
# Sketchybar is macOS-only, but emitting this file on Linux is harmless
# (sketchybar's other dotfile entries also symlink platform-blindly).
{ config, lib, ... }:

let
  c = config.lib.stylix.colors.withHashtag;
  # Strip the leading '#' from a stylix hex string ("#rrggbb" -> "rrggbb").
  raw = h: lib.removePrefix "#" h;
  # Build a sketchybar AARRGGBB color literal: 0x + alpha byte + rrggbb.
  argb = alpha: hex: "0x${alpha}${raw hex}";
in
{
  config.xdg.configFile."sketchybar/colors.sh".text = ''
    #!/usr/bin/env bash
    # shellcheck disable=SC2034  # variables are sourced by other scripts
    # Generated by Nix from myOptions.theme + stylix base16 palette.
    # Do not edit by hand; change `myOptions.theme.scheme` and rebuild.
    #
    # Var → base16 slot mapping:
    #   COLOR_CYAN     base0C   COLOR_BLACK    base01   COLOR_GRAY    base02
    #   COLOR_MAGENTA  base0E   COLOR_PINK     base0F   COLOR_RED     base08
    #   COLOR_GREEN    base0B   COLOR_YELLOW   base0A   COLOR_BLUE    base0D
    #   COLOR_ORANGE   base09   COLOR_BLACK4   base04   COLOR_WHITE   base05
    #   COLOR_ICON_SECONDARY / COLOR_LABEL_SECONDARY  base06

    # Base Palette
    COLOR_CYAN=${argb "ff" c.base0C}
    COLOR_BLACK=${argb "ff" c.base01}
    COLOR_GRAY=${argb "ff" c.base02}
    COLOR_MAGENTA=${argb "ff" c.base0E}
    COLOR_PINK=${argb "ff" c.base0F}
    COLOR_RED=${argb "ff" c.base08}
    COLOR_GREEN=${argb "ff" c.base0B}
    COLOR_YELLOW=${argb "ff" c.base0A}
    COLOR_BLUE=${argb "ff" c.base0D}
    COLOR_ORANGE=${argb "ff" c.base09}
    COLOR_BLACK4=${argb "ff" c.base04}
    COLOR_WHITE=${argb "ff" c.base05}

    # Semantic Colors
    COLOR_BACKGROUND=${argb "50" c.base00}
    COLOR_BACKGROUND_SECONDARY=${argb "40" c.base03}
    COLOR_BACKGROUND_TERTIARY=${argb "30" c.base04}
    COLOR_ITEM_BACKGROUND=${argb "40" c.base02}
    COLOR_FOREGROUND=$COLOR_WHITE
    COLOR_BORDER=${argb "66" c.base05}
    COLOR_ACCENT=$COLOR_BLUE

    # Icon and Label Colors
    COLOR_ICON=$COLOR_WHITE
    COLOR_ICON_HIGHLIGHT=$COLOR_BLUE
    COLOR_ICON_SECONDARY=${argb "ff" c.base06}
    COLOR_LABEL=$COLOR_WHITE
    COLOR_LABEL_SECONDARY=${argb "ff" c.base06}

    # Popup Colors
    COLOR_POPUP_BACKGROUND=${argb "f0" c.base00}
    COLOR_POPUP_BORDER=$COLOR_BLUE

    # Status Colors
    COLOR_SUCCESS=$COLOR_GREEN
    COLOR_WARNING=$COLOR_YELLOW
    COLOR_ERROR=$COLOR_RED
    COLOR_INFO=$COLOR_CYAN
  '';
}
