# Palette for the Claude Code status line, rendered from the active base16
# scheme so it recolours with the rest of the system on a
# `myOptions.theme.scheme` change.
#
# Only the palette lives here. The renderer itself is a package
# (public/overlays/claude-statusline-render) because Claude Code's `statusLine`
# is system-scope managed settings, which cannot see Home Manager config — so
# the two halves meet at this file path rather than through the module system.
# Slots the renderer does not draw with are omitted; it ignores unknown keys and
# falls back to its own defaults for any it does not find here.
#
# Same pattern as `sketchybar.nix` / `nvim-theme.nix`: a generated file, NOT a
# live-edit dotfile — change this module and rebuild rather than editing the
# result, which the next activation overwrites.
{ config, ... }:

let
  # Bare hex, no leading '#': the renderer parses each value as three hex byte
  # pairs to build an ANSI truecolor escape.
  c = config.lib.stylix.colors;
in
{
  xdg.configFile."claude-statusline/theme.env".text = ''
    # Generated by Nix — see modules/shared/home/ai/claude-statusline.nix.
    # Do not edit by hand; change `myOptions.theme.scheme` and rebuild.
    base03=${c.base03}
    base08=${c.base08}
    base09=${c.base09}
    base0A=${c.base0A}
    base0B=${c.base0B}
    base0C=${c.base0C}
    base0D=${c.base0D}
    base0E=${c.base0E}
  '';
}
